Make The Demo Multilingual
IEvangelist/blazor-azure-openai pull request #5
Opened 2023-04-02 19:43 UTC by Husseinbeygi

Here's what happened in this PR : 

1. Added Localization 
2. Added a DataDictionary for unified resources 
3. Change all texts to read from datadictionary
4. Add RTL support for Persian and Arabic (don't know what language are RTL beside these two! :) )
5. Added DataDictionary.fa.resx for test

2023-04-03 13:35 UTC, IEvangelist requested changes
Hi @Husseinbeygi - thank you so much for your PR, this looks awesome! With that said, I do have some nits and suggestions for improvement, and one larger concern. I would love for us to use isolate resource files to components. And when there are shared resources, we could then use the `DataDictionary` approach. Does that make sense?

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Extensions/Localization.cs
> +
```suggestion
```

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Pages/VoiceChat.razor.cs
> +        var dialog = await Dialog.ShowAsync<VoiceDialog>(title: DataDictionary.TTPPreferences);
```suggestion
        var dialog = await Dialog.ShowAsync<VoiceDialog>(title: DataDictionary.TTSPreferences);
```

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Extensions/Localization.cs
> +    internal  static async Task ConfigCulture(WebAssemblyHost host)
```suggestion
    internal static async Task ConfigCulture(this WebAssemblyHost host)
```

This is in the _Extensions_ folder, but it's not an extension. Let's change that.

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Program.cs
> +
```suggestion
```

Let's make this a global using, add it to the _GlobalUsings.cs_ file instead.

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Program.cs
> +await Localization.ConfigCulture(host);
```suggestion
await host.ConfigCulture();
```

Use it as an extension method.

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Shared/CultureSelector.razor
> +			   Style="width:120px !important">
```suggestion
			   Style="width:10rem">
```

Let's try to avoid `px` and `!important`, instead let's try to use `rem` or `em`, and add the appropriate specifiers/selectors. As an inline style, it likely wouldn't need the `!important` anyway.

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/wwwroot/css/app.css
> +{
```suggestion
.rtl-lang {
```

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Shared/MainLayout.razor
>  @code {
```suggestion

@code {
```

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Shared/CultureSelector.razor
> +{
```suggestion
@code {

    [Inject] public required ILocalStorageService LocalStorage { get; set; }
```

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/wwwroot/index.html
> +	</script>
```suggestion
```

Let's avoid this kind of logic, and instead, use the `Blazor.LocalStorage.WebAssembly` package that's already in use in this project. This would be deleted.

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Shared/Resources/DataDictionary.resx
Let's name this file as _DataDictionary.en.resx_

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Shared/CultureSelector.razor
> +@inject IJSRuntime JS
```suggestion
```

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Shared/CultureSelector.razor
> +				js.InvokeVoid("blazorCulture.set", value.Name);
```suggestion
				LocalStorage.SetItem(
				    "blazor-openai-client-culture", value.Name);
```

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Shared/MainLayout.razor
> +	}
```suggestion
	bool _isRightToLeft =>
	    Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName is "fa" or "ar";
```

Simplify this expression, such that it's only evaluated the two letter ISO once with pattern matching.

2023-04-03 13:35 UTC, IEvangelist commented on Azure.OpenAI/Client/Extensions/Localization.cs
> +        CultureInfo.DefaultThreadCurrentUICulture = culture;
```suggestion
        var localStorage = host.Services.GetRequiredService<ILocalStorageService>();
        var clientCulture = localStorage.GetItem<string>("blazor-openai-client-culture");
        clientCulture ??= "en";

        CultureInfo culture = new(clientCulture);
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
```

2023-04-03 16:29 UTC, Husseinbeygi commented
> Hi @Husseinbeygi - thank you so much for your PR, this looks awesome! With that said, I do have some nits and suggestions for improvement, and one larger concern. I would love for us to use isolate resource files to components. And when there are shared resources, we could then use the `DataDictionary` approach. Does that make sense?

Hi @IEvangelist, thank you for considering. 
How about move resources files to its own class library and then with appropriate static class isolate the texts from components 
I mean instead of this
` <text>@DataDictionary.SomeText</text> `
we use this 
```
class static DataDictionaryClass
{
        public static string SomeText => Resources.DataDictionary.SomeText
}
<text>@DataDictionaryClass.SomeText</text>
```

This is what you have in mind? 
please correct me if I'm wrong.

2023-04-03 16:40 UTC, Husseinbeygi commented on Azure.OpenAI/Client/Shared/MainLayout.razor
> +	}
Beautiful😍

2023-04-03 16:48 UTC, Husseinbeygi reviewed
The `LocalStorage` in CultureSelector is Blazored/LocalStorage ?
Do I install the package?

2023-04-03 17:02 UTC, Husseinbeygi commented on Azure.OpenAI/Shared/Resources/DataDictionary.resx
Done.

2023-04-03 17:43 UTC, Husseinbeygi commented
> > > Hi @Husseinbeygi - thank you so much for your PR, this looks awesome! With that said, I do have some nits and suggestions for improvement, and one larger concern. I would love for us to use isolate resource files to components. And when there are shared resources, we could then use the `DataDictionary` approach. Does that make sense?
> > 
> > 
> > Hi @IEvangelist, thank you for considering. How about move resources files to its own class library and then with appropriate static class isolate the texts from components I mean instead of this `<text>@DataDictionary.SomeText</text>` we use this
> > ```
> > class static DataDictionaryClass
> > {
> >         public static string SomeText => Resources.DataDictionary.SomeText
> > }
> > <text>@DataDictionaryClass.SomeText</text>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is what you have in mind? please correct me if I'm wrong.
> 
> Hi @Husseinbeygi - I was thinking more along the lines of having the localized resources nested under each component where they're used, and only having a shared resource for common translations. For example, the `VoiceChat` component would have the following:
> 
> * _VoiceChat.razor_
> * _VoiceChat.razor.cs_
> * _VoiceChat.razor.en.resx_
> * _VoiceChat.razor.fa.resx_
> 
> And the resources for these nested files only correspond to the `VoiceChat` component. This pattern would then be repeated as needed on a component-by-component basis.

In this case 
I'll follow the approach in [Localize .NET applications with machine-translation
](https://devblogs.microsoft.com/dotnet/localize-net-applications-with-machine-translation/)

2023-04-03 20:00 UTC, IEvangelist commented on Azure.OpenAI/Client/Extensions/Localization.cs
> +internal sealed class Localization
```suggestion
internal static class Localization
```

Extensions have to be in static classes.

2023-04-03 20:06 UTC, Husseinbeygi commented on Azure.OpenAI/Client/Extensions/Localization.cs
> +internal sealed class Localization
Yeah 
I fixed it in forked code.

2023-04-03 21:07 UTC, Husseinbeygi commented
> > Hi @Husseinbeygi - I was thinking more along the lines of having the localized resources nested under each component where they're used, and only having a shared resource for common translations. For example, the `VoiceChat` component would have the following:
> > 
> > * _VoiceChat.razor_
> > * _VoiceChat.razor.cs_
> > * _VoiceChat.razor.en.resx_
> > * _VoiceChat.razor.fa.resx_
> > 
> > And the resources for these nested files only correspond to the `VoiceChat` component. This pattern would then be repeated as needed on a component-by-component basis.
> 
> In this case I'll follow the approach in [Localize .NET applications with machine-translation ](https://devblogs.microsoft.com/dotnet/localize-net-applications-with-machine-translation/)

Done!
Note : due to the fact that when we run the Azure Cognitive Services Translator workflow, there will be a lot of files 
I created a folder for the pages that had the `*.resx` file
I hope that's okay!

2023-04-03 21:27 UTC, IEvangelist approved these changes

2023-04-03 21:29 UTC, merged

2023-04-05 14:59 UTC, IEvangelist commented
Hey @Husseinbeygi - check it out, I did a bit of cleaning up, and then I also added the localization automation with the GitHub Action workflow:

- Here's a PR that it generated: https://github.com/IEvangelist/blazor-azure-openai/pull/8
- I made the language selector a modal dialog: https://github.com/IEvangelist/blazor-azure-openai/commit/43988793f62dd0f92ac5ac48b96634b8931b04b8